### ISSUE TITLE
EHDOC draft changed url

### ISSUE THREAD

**Issue by lu-zero** [martindisch/oscore#3]
[edhoc](https://datatracker.ietf.org/doc/draft-ietf-lake-edhoc/) is now part of [lake](https://datatracker.ietf.org/wg/lake/documents/).

**Comment by martindisch** [comment]
Thanks for the heads-up! I updated the reference to the current version in 6f8f4571ee5556ddcfac70289173800eeeefc234 but left a mention of the older version that this actually implements. Let me know if I forgot something.
